
spring:
  datasource:
    url: jdbc:sqlite:taxiService.db
    driver-class-name: org.sqlite.JDBC
    username: root
    password: 1234
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLiteDialect
    open-in-view: false
    show-sql: true
#    hibernate:
#      ddl-auto: create
